- complete/pom.xml
- complete/src/main/java/com/example/restservice/config/SwaggerConfig.java
- complete/src/main/java/com/example/restservice/constants/UserStatus.java
- complete/src/main/java/com/example/restservice/constants/UserStatusConstants.java
- complete/src/main/java/com/example/restservice/controller/QueueController.java
- complete/src/main/java/com/example/restservice/controller/UserController.java
- complete/src/main/java/com/example/restservice/dao/UserDao.java
- complete/src/main/java/com/example/restservice/model/DeleteUserRequest.java
- complete/src/main/java/com/example/restservice/model/JoinQueueRequest.java
- complete/src/main/java/com/example/restservice/model/Queue.java
- complete/src/main/java/com/example/restservice/model/QueueDetailsRequest.java
- complete/src/main/java/com/example/restservice/model/QueueDetailsResponse.java
- complete/src/main/java/com/example/restservice/model/User.java
- complete/src/main/java/com/example/restservice/model/UserStatusRequest.java
- complete/src/main/java/com/example/restservice/model/UserStatusResponse.java
- complete/src/main/java/com/example/restservice/service/QueueService.java
- complete/src/main/java/com/example/restservice/service/UserService.java
- complete/src/main/java/com/example/restservice/service/smsService/SmsConstants.java
- complete/src/main/java/com/example/restservice/service/smsService/SmsManager.java
- complete/src/main/java/com/example/restservice/service/smsService/SmsService.java
- complete/src/main/java/com/example/restservice/service/smsService/TexLocalSmsService.java
- complete/src/main/resources/application.properties
> Backend Working, yet to integrate

- complete/pom.xml
- complete/src/main/java/com/example/restservice/dao/DaoBase.java
- complete/src/main/java/com/example/restservice/model/User.java
The program uses RDS/PostgreSQL if run on AWS, but on local dev machines, uses H2
> AWS RDS Setup

- .idea/workspace.xml
- complete/pom.xml
- complete/src/main/java/com/example/restservice/controller/QueueController.java
- complete/src/main/java/com/example/restservice/controller/advices/LoggedInUserInfo.java
- complete/src/main/java/com/example/restservice/controller/advices/SecurityAdvice.java
- complete/src/main/java/com/example/restservice/dao/Queue.java
- complete/src/main/java/com/example/restservice/dao/User.java
- complete/src/main/java/com/example/restservice/model/CreateQueueRequest.java
- complete/src/main/java/com/example/restservice/service/QueueService.java
Pretty naive approach, will have to think of better ways of doing this.
> Auth: Add Owner information to DB

- complete/src/main/java/com/example/restservice/RestServiceApplication.java
- complete/src/main/java/com/example/restservice/config/DataSourceConfig.java
- complete/src/main/java/com/example/restservice/config/SwaggerConfig.java
- complete/src/main/java/com/example/restservice/dao/Queue.java
- complete/src/main/java/com/example/restservice/dao/QueueRepository.java
- complete/src/main/java/com/example/restservice/exceptions/SQInvalidRequestException.java
- complete/src/main/java/com/example/restservice/model/CreateQueueRequest.java
- complete/src/main/java/com/example/restservice/model/CreateQueueResponse.java
- complete/src/main/java/com/example/restservice/model/DeleteUserRequest.java
- complete/src/main/java/com/example/restservice/model/JoinQueueRequest.java
- complete/src/main/java/com/example/restservice/model/QueueDetailsRequest.java
- complete/src/main/java/com/example/restservice/model/QueueDetailsResponse.java
- complete/src/main/java/com/example/restservice/model/UserStatusRequest.java
- complete/src/main/java/com/example/restservice/model/UserStatusResponse.java
- complete/src/main/java/com/example/restservice/service/QueueService.java
Resolving conficts and applying the google-java-format jar to all java files.
Will test the GitHub action too.
> Java code format

- Scripts/runJar.sh
- complete/src/main/java/com/example/restservice/controller/QueueController.java
- complete/src/main/java/com/example/restservice/controller/TokenController.java
- complete/src/main/java/com/example/restservice/controller/model/queue/CreateQueueResponse.java
- complete/src/main/java/com/example/restservice/controller/model/queue/MyQueuesResponse.java
- complete/src/main/java/com/example/restservice/controller/model/queue/QueueDetailsResponse.java
- complete/src/main/java/com/example/restservice/controller/model/queue/QueueStatusResponse.java
- complete/src/main/java/com/example/restservice/controller/model/token/CreateTokenRequest.java
- complete/src/main/java/com/example/restservice/controller/model/token/MyTokensResponse.java
- complete/src/main/java/com/example/restservice/controller/model/token/TokenDeleteResponse.java
- complete/src/main/java/com/example/restservice/controller/model/token/TokenDetailResponse.java
- complete/src/main/java/com/example/restservice/controller/model/token/TokenNotifyResponse.java
- complete/src/main/java/com/example/restservice/dao/Token.java
- complete/src/main/java/com/example/restservice/service/QueueService.java
- complete/src/main/java/com/example/restservice/service/TokenService.java
- complete/src/main/java/com/example/restservice/service/smsService/SmsManager.java
1. Constructor Autowiring so that autowired fields can be final
2. Final for other fileds
3. Fix typo in notifiable
4. Standardise lombok annotations
> Eng Debt: Mark fields final, fix typo and others

- complete/src/main/java/com/example/restservice/controller/model/queue/QueueDetailsResponse.java
- complete/src/main/java/com/example/restservice/controller/model/token/TokenDetailResponse.java
- complete/src/main/java/com/example/restservice/dao/Token.java
- complete/src/main/java/com/example/restservice/dao/TokenRepository.java
- complete/src/main/java/com/example/restservice/service/TokenService.java
> Add token number field to token object

- complete/src/main/java/com/example/restservice/service/SecretsManager.java
- complete/src/main/java/com/example/restservice/service/smsService/MockSmsService.java
- complete/src/main/java/com/example/restservice/service/smsService/TexLocalSmsService.java
- complete/src/main/resources/application-dev.properties
- complete/src/main/resources/application-local.properties
- complete/src/main/resources/application-prod.properties
- complete/src/main/resources/application.properties
This PR is used to address #66
> Changes to manage env variables using spring profiles

- complete/src/main/java/com/example/restservice/dao/QueueRepository.java
- complete/src/main/java/com/example/restservice/dao/TokenRepository.java
- complete/src/main/java/com/example/restservice/service/QueueService.java
Solves #81 
Throwing proper error on creating queue when the name is already taken.
Fix: https://stackoverflow.com/questions/54876448/how-to-catch-hibernate-constraintviolationexception-or-spring-dataintegrityviol
> Switch to JpaRepository 

- README.md
- pom.xml
- simplq/pom.xml
> Parent pom implementation in root

- simplq/pom.xml
- simplq/src/main/java/me/simplq/controller/advices/AuthenticationFilter.java
- simplq/src/main/resources/application.properties
We decided to switch to auth0, more information here: https://github.com/SimplQ/simplQ-frontend/issues/461
Auth0 switch frontend PR: https://github.com/SimplQ/simplQ-frontend/pull/483
> Add Auth0 as a identity provider

- .github/workflows/build.yml
- .gitignore
- simplq/pom.xml
- simplq/src/main/java/me/simplq/controller/QueueController.java
- simplq/src/main/java/me/simplq/controller/model/queue/PatchQueueRequest.java
- simplq/src/main/java/me/simplq/controller/model/queue/PatchQueueResponse.java
- simplq/src/main/java/me/simplq/dao/Queue.java
- simplq/src/main/java/me/simplq/service/QueueService.java
- simplq/src/test/java/me/simplq/IntegrationTests.java
- simplq/src/test/java/me/simplq/service/QueueServiceTest.java
https://github.com/SimplQ/simplQ-backend/issues/111
> Max capacity queue

- .github/workflows/build.yml
- .github/workflows/google_java_format.yml
Add `--no-transfer-progress` to mvn package in unit test
Run GJF also on PRs
> Github Action Minor improvements

- simplq/pom.xml
- simplq/src/main/resources/db/changeset.log.xml
Minor changes to make the migrations to work on the backend server.
> Minor Fixes to get migrations to work on CI

- simplq/src/main/java/me/simplq/controller/model/queue/QueueDetailsResponse.java
- simplq/src/main/java/me/simplq/service/QueueService.java
The status was not exposed when GETing queue resource.
> Expose queue status when getting queue

- simplq/src/main/java/me/simplq/controller/model/queue/PatchQueueResponse.java
- simplq/src/main/java/me/simplq/controller/model/queue/QueueDetailsResponse.java
- simplq/src/main/java/me/simplq/controller/model/queue/QueueStatusResponse.java
- simplq/src/main/java/me/simplq/dao/Queue.java
- simplq/src/main/java/me/simplq/exceptions/SQInvalidRequestException.java
- simplq/src/main/java/me/simplq/service/QueueService.java
- simplq/src/main/java/me/simplq/service/TokenService.java
- simplq/src/test/java/me/simplq/IntegrationTests.java
Resolves https://github.com/SimplQ/simplQ-backend/issues/111
> Finish max queue capacity tasks

- simplq/src/main/java/me/simplq/config/WebConfig.java
https://stackoverflow.com/questions/38250192/spring-security-cors-filter-not-working
> Fix cors - next attempt 

- simplq/src/main/resources/db/changeset.log.xml
> Fix: Remove unique constraint from name column of token

- simplq/src/main/java/me/simplq/service/OwnerService.java
Fixed as per comments in 
#148 
Please review and me know if any changes needed. 
Thanks!
> Use orElseGet instead of orElse in OwnerService.getOwnerOrElseCreate

- .github/workflows/google_java_format.yml
ref https://github.com/axel-op/googlejavaformat-action/issues/11
> Update google_java_format.yml to solve commit failure

- simplq/src/main/resources/db/changeset.log.xml
Add extra column required for #154
> add column token_deletion_timestamp

- simplq/src/main/java/me/simplq/controller/QueueController.java
- simplq/src/main/java/me/simplq/controller/model/queue/QueueDetailsResponse.java
- simplq/src/main/java/me/simplq/controller/model/queue/QueueEventsResponse.java
- simplq/src/main/java/me/simplq/service/QueueEventsService.java
- simplq/src/main/java/me/simplq/service/QueueService.java
- simplq/src/test/java/me/simplq/service/QueueEventsServiceTest.java
- simplq/src/test/java/me/simplq/service/QueueServiceTest.java
Add queue events to suport queue history, ref https://github.com/SimplQ/simplQ-backend/issues/126#issuecomment-904993443
> Add queue events API

- simplq/src/main/java/me/simplq/service/TokenService.java
Resolves https://github.com/SimplQ/simplQ-backend/issues/179
> Set transactions to serialized isolation level while creating tokens
